[package]
name = "gmodstore_offers"
version = "0.1.0"
edition = "2024"

[dependencies]
headless_chrome = "1.0.17"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.140", features = ["derive"] }
